aws:
  accessKey: AKIA3C2XA22LEPAELRTG
  secretKay: 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
  cognitoPool:
    clientId: 45l9uo6l5t7l3l3201j783qlsu
    clientSecret: 1uh4iafogm91u9oo63g0donncfomjgod74e9ktk873727o48vlsm