aws:
  accessKey: XXX
  secretKay: XXX
  cognitoPool:
    poolName: thapro
    poolId: ap-southeast-1_0KzqzRNXe
    clientId: XXX
    clientSecret: XXX
google:
  clientId : XXXX
  clientSecret: XXXX
  redirectUri: https://supersacred-nonpersonally-danna.ngrok-free.dev/auth/apple-authoriz-callback
  grantType: authorization_code
  tokenEndPoint: https://oauth2.googleapis.com/token
  frontEndRedirectUrl : http://localhost:3000/google-callback
apple:
  clientId : mosaic.green.apple.login
  #redirectUri: https://supersacred-nonpersonally-danna.ngrok-free.dev/apple-callback
  redirectUri: https://supersacred-nonpersonally-danna.ngrok-free.dev/auth/apple-authoriz-callback
  grantType: authorization_code
  tokenEndPoint: https://appleid.apple.com/auth/token
  signinKeyName: XXXXX
  signinKeyId : XXXX
  teamId: XXXX
  frontEndRedirectUrl : http://localhost:3000/apple-callback