aws:
  accessKey: XXX
  secretKay: XXXX
  cognitoPool:
    poolName: thapro
    poolId: ap-southeast-1_0KzqzRNXe
    clientId: 72gr39uikuuse1t12j8tp6rt6h
    clientSecret: XXXX
google:
  clientId : 304677613464-1a3fdbp3kpg9afuu8jdv13860i4gk2f9.apps.googleusercontent.com
  clientSecret: XXXX
  redirectUri: http://localhost:3000/google-callback
  grantType: authorization_code
  tokenEndPoint: https://oauth2.googleapis.com/token